### ISSUE TITLE
3 ants window title is left aligned on Windows 11

### ISSUE THREAD

**Issue by maacl** [tonsky/humble-ants#1]
Cf title.

![image](https://user-images.githubusercontent.com/64092/216770072-706d2061-8d18-4d7c-b7ee-a94f7c9f8361.png)

**Comment by tonsky** [comment]
Aren’t all window titles left-aligned in Windows?

**Comment by maacl** [comment]
Yes. I saw the screenshot and thought your intend was for it to be centered on all platforms, my bad.
